---
title: "Ch6 HW - Housing Credit Analysis"
author: "Hannah Wagner, Asha Bazil"
date: "10/26/2020"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
options(scipen=10000000)

library(tidyverse)
library(caret)
library(knitr) 
library(pscl)
library(plotROC)
library(pROC)
library(scales)
library(kableExtra)
library(grid)
library(gridExtra)

root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette5 <- c("#981FAC","#CB0F8B","#FF006A","#FE4C35","#FE9900")
palette4 <- c("#981FAC","#FF006A","#FE4C35","#FE9900")
palette2 <- c("#981FAC","#FF006A")

credit <- read.csv(file.path(root.dir,"/Chapter6/housingSubsidy.csv"))

iterateThresholds <- function(data, observedClass, predictedProbs, group) {
  #This function takes as its inputs, a data frame with an observed binomial class (1 or 0); a vector of predicted probabilities; and optionally a group indicator like race. It returns accuracy plus counts and rates of confusion matrix outcomes. It's a bit verbose because of the if (missing(group)). I don't know another way to make an optional parameter.
  observedClass <- enquo(observedClass)
  predictedProbs <- enquo(predictedProbs)
  group <- enquo(group)
  x = .01
  all_prediction <- data.frame()
  
  if (missing(group)) {
    
    while (x <= 1) {
      this_prediction <- data.frame()
      
      this_prediction <-
        data %>%
        mutate(predclass = ifelse(!!predictedProbs > x, 1,0)) %>%
        count(predclass, !!observedClass) %>%
        summarize(Count_TN = sum(n[predclass==0 & !!observedClass==0]),
                  Count_TP = sum(n[predclass==1 & !!observedClass==1]),
                  Count_FN = sum(n[predclass==0 & !!observedClass==1]),
                  Count_FP = sum(n[predclass==1 & !!observedClass==0]),
                  Rate_TP = Count_TP / (Count_TP + Count_FN),
                  Rate_FP = Count_FP / (Count_FP + Count_TN),
                  Rate_FN = Count_FN / (Count_FN + Count_TP),
                  Rate_TN = Count_TN / (Count_TN + Count_FP),
                  Accuracy = (Count_TP + Count_TN) / 
                    (Count_TP + Count_TN + Count_FN + Count_FP)) %>%
        mutate(Threshold = round(x,2))
      
      all_prediction <- rbind(all_prediction,this_prediction)
      x <- x + .01
    }
    return(all_prediction)
  }
  else if (!missing(group)) { 
    while (x <= 1) {
      this_prediction <- data.frame()
      
      this_prediction <-
        data %>%
        mutate(predclass = ifelse(!!predictedProbs > x, 1,0)) %>%
        group_by(!!group) %>%
        count(predclass, !!observedClass) %>%
        summarize(Count_TN = sum(n[predclass==0 & !!observedClass==0]),
                  Count_TP = sum(n[predclass==1 & !!observedClass==1]),
                  Count_FN = sum(n[predclass==0 & !!observedClass==1]),
                  Count_FP = sum(n[predclass==1 & !!observedClass==0]),
                  Rate_TP = Count_TP / (Count_TP + Count_FN),
                  Rate_FP = Count_FP / (Count_FP + Count_TN),
                  Rate_FN = Count_FN / (Count_FN + Count_TP),
                  Rate_TN = Count_TN / (Count_TN + Count_FP),
                  Accuracy = (Count_TP + Count_TN) / 
                    (Count_TP + Count_TN + Count_FN + Count_FP)) %>%
        mutate(Threshold = round(x,2))
      
      all_prediction <- rbind(all_prediction,this_prediction)
      x <- x + .01
    }
    return(all_prediction)
  }
}

```

## Introduction

TODO

```{r visualization of features}
# Continuous variables
credit %>%
  dplyr::select(y, age, previous, unemploy_rate, cons.price.idx, cons.conf.idx, inflation_rate, spent_on_repairs) %>%
  gather(Variable, value, -y) %>%
  ggplot(aes(y, value, fill=y)) + 
  geom_bar(position = "dodge", stat = "summary", fun = "mean") + 
  facet_wrap(~Variable, scales = "free") +
  scale_fill_manual(values = palette2) +
  labs(x="Credit Uptake", y="Mean", 
       title = "Feature associations with the likelihood of credit uptake",
       subtitle = "(continous outcomes)") +
  plotTheme() + theme(legend.position = "none")

#Binary variables
credit %>%
  dplyr::select(y,taxLien, mortgage, taxbill_in_phl) %>%
  gather(Variable, value, -y) %>%
  count(Variable, value, y) %>%
  filter(value == "yes") %>%
  ggplot(aes(y, n, fill = y)) +   
  geom_bar(position = "dodge", stat="identity") +
  facet_wrap(~Variable, scales = "free") +
  scale_fill_manual(values = palette2) +
  labs(x="Credit Uptake", y="Count",
       title = "Feature associations with the likelihood of credit uptake",
       subtitle = "Two category features (Yes and No)") +
  plotTheme() + theme(legend.position = "none")

#Categorical variables
credit %>%
  dplyr::select(y, job, marital, education, contact, month, day_of_week, campaign, pdays, poutcome) %>%
  gather(Variable, value, -y) %>%
  count(Variable, value, y) %>%
  ggplot(aes(value, n, fill = y)) +   
  geom_bar(position = "dodge", stat="identity") +
  facet_wrap(~Variable, scales="free") +
  scale_fill_manual(values = palette2) +
  labs(x="Credit Uptake", y="Count",
       title = "Feature associations with the likelihood of credit uptake",
       subtitle = "Multiple category features") +
  plotTheme() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Initial Model Creation



```{r model creation}
#Split into 65/35 training/test set

set.seed(3456)
trainIndex <- createDataPartition(credit$y, p = .65,
                                  list = FALSE,
                                  times = 1)
creditTrain <- credit[ trainIndex,]
creditTest  <- credit[-trainIndex,]

#kitchen sink model

reg1 <- glm(y_numeric ~ .,
            data=creditTrain %>% dplyr::select(-y,-taxLien),
            family="binomial" (link="logit"))

summary(reg1)
testProbs <- data.frame(Outcome = as.factor(creditTest$y_numeric),
                        Probs = predict(reg1, creditTest, type= "response"))
testProbs <- 
  testProbs %>%
  mutate(predOutcome  = as.factor(ifelse(testProbs$Probs > 0.5 , 1, 0)))

caret::confusionMatrix(testProbs$predOutcome, testProbs$Outcome, 
                       positive = "1")

#new feature engineering
#TODO
credit_engineer <-
 credit%>%
  mutate(higherEd=ifelse(education=="professional.course"| education =="university.degree","yes","no"),
         over50=ifelse(age>50, "yes","no"),
         infl_over3.6=ifelse(inflation_rate>3.6,"yes","no"),
         previous_contact=ifelse(previous>0,"yes","no"),
         high_skill_work=ifelse(job=="admin" | job=="entrepreneur" | job == "management" | job=="self-employed" | job=="technician", "yes", "no"))

#Binary variables
credit_engineer%>%
  dplyr::select(y, higherEd, over50, infl_over3.6, previous_contact, high_skill_work) %>%
  gather(Variable, value, -y) %>%
  count(Variable, value, y) %>%
  filter(value == "yes") %>%
  ggplot(aes(y, n, fill = y)) +   
  geom_bar(position = "dodge", stat="identity") +
  facet_wrap(~Variable, scales = "free") +
  scale_fill_manual(values = palette2) +
  labs(x="Credit Uptake", y="Count",
       title = "Feature associations with the likelihood of credit uptake",
       subtitle = "Two category features (Yes and No)") +
  plotTheme() + theme(legend.position = "none")

plot(credit_engineer$cons.price.idx, credit_engineer$cons.conf.idx)
plot(credit_engineer$cons.price.idx, credit_engineer$unemploy_rate)
plot(credit_engineer$cons.conf.idx, credit_engineer$unemploy_rate)

# number of no entries = 3668 vs. number of yes entries = 451

#engineered model
#dv <- c("y_numeric")
#ivs <- c("X", "marital", "mortgage", "taxbill_in_phl", "contact", "month", "day_of_week", "campaign", "pdays", "previous",
 #        "poutcome", "cons.price.idx", "cons.conf.idx", "spent_on_repairs", "y_numeric",
  #       "higherEd","over50","infl_over3.6", "previous_contact","high_skill_work")

#data.cleaned <- data.cleaned.allvars %>%
 #   dplyr::select(c(ivs,dv,addlVariablesToKeep)) %>%
  #  dplyr::distinct(.keep_all=TRUE)

#data.known <- data.cleaned %>% dplyr::filter(toPredict==0) %>% distinct(.keep_all=TRUE)
#data.unknown <- data.cleaned %>% dplyr::filter(toPredict==1)


creditTrain_eng <- credit_engineer[ trainIndex,]
creditTest_eng  <- credit_engineer[-trainIndex,]

reg_eng <- glm(y_numeric ~ .,
            data=creditTrain_eng %>% 
            dplyr::select(-y,-taxLien,-age,-job,-education,-unemploy_rate, 
                          -inflation_rate),
            family="binomial" (link="logit"))

summary(reg_eng)

testProbs_eng <- data.frame(Outcome = as.factor(creditTest_eng$y_numeric),
                        Probs = predict(reg_eng, creditTest_eng, type= "response"))
testProbs_eng <- 
  testProbs_eng %>%
  mutate(predOutcome  = as.factor(ifelse(testProbs_eng$Probs > 0.5 , 1, 0)))

caret::confusionMatrix(testProbs_eng$predOutcome, testProbs_eng$Outcome, 
                       positive = "1")

```


## CV of both models

```{r cv both models}

#kitchen sink model CV
ctrl <- trainControl(method = "cv", number = 100, classProbs=TRUE, summaryFunction=twoClassSummary)

#cvFit <- train(y ~ ., data = credit %>% 
 #                dplyr::select(
  #                 -y_numeric), 
   #            method="glm", family="binomial",
    #           metric="ROC", trControl = ctrl)

#cvFit

cvFit.reg1 <- train(y ~ ., data = credit %>%
                      dplyr::select(-y_numeric, -X) %>%
                      dplyr::mutate(y = ifelse(y=="yes","c1.yes","c2.no")), 
                    method="glm", family="binomial",
                    metric="ROC", trControl = ctrl)
#kitchen sink plots

dplyr::select(cvFit.reg1$resample, -Resample) %>%
  gather(metric, value) %>%
  left_join(gather(cvFit.reg1$results[2:4], metric, mean)) %>%
  ggplot(aes(value)) + 
  geom_histogram(bins=35, fill = "#FF006A") +
  facet_wrap(~metric) +
  geom_vline(aes(xintercept = mean), colour = "#981FAC", linetype = 3, size = 1.5) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x="Goodness of Fit", y="Count", title="CV Goodness of Fit Metrics",
       subtitle = "Across-fold mean reprented as dotted lines") +
  plotTheme()

#engineered model CV

#TODO
cvFit.reg_eng <- train(y ~ ., data = credit_engineer %>%
                      dplyr::select(-y_numeric, -X,-taxLien,-age,-job,-education,-unemploy_rate, 
                          -inflation_rate) %>%
                      dplyr::mutate(y = ifelse(y=="yes","c1.yes","c2.no")), 
                    method="glm", family="binomial",
                    metric="ROC", trControl = ctrl)

#engineered model plots
#TODO
dplyr::select(cvFit.reg_eng$resample, -Resample) %>%
  gather(metric, value) %>%
  left_join(gather(cvFit.reg_eng$results[2:4], metric, mean)) %>%
  ggplot(aes(value)) + 
  geom_histogram(bins=35, fill = "#FF006A") +
  facet_wrap(~metric) +
  geom_vline(aes(xintercept = mean), colour = "#981FAC", linetype = 3, size = 1.5) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x="Goodness of Fit", y="Count", title="CV Goodness of Fit Metrics",
       subtitle = "Across-fold mean reprented as dotted lines") +
  plotTheme()


```


## ROC of engineered model


```{r ROC}

rocEngineered <-
ggplot(testProbs_eng, aes(d = as.numeric(testProbs_eng$Outcome), m = Probs)) +
  geom_roc(n.cuts = 50, labels = FALSE, colour = "#FE9900") +
  style_roc(theme = theme_grey) +
  geom_abline(slope = 1, intercept = 0, size = 1.5, color = 'grey') +
  labs(title = "ROC Curve - engineered model")

rocEngineered

```


## Cost Benefit Analysis


```{r CB table}
#Generating Costs and Benefits
cost_benefit_table <-
  testProbs_eng %>%
  count(predOutcome, Outcome) %>%
  summarize(True_Negative = sum(n[predOutcome==0 & Outcome==0]),
            True_Positive = sum(n[predOutcome==1 & Outcome==1]),
            False_Negative = sum(n[predOutcome==0 & Outcome==1]),
            False_Positive = sum(n[predOutcome==1 & Outcome==0])) %>%
  gather(Variable, Count) %>%
  mutate(Revenue =
           case_when(Variable == "True_Negative"  ~ Count * 0,
                     Variable == "True_Positive"  ~ Count * 8650,
                     Variable == "False_Negative" ~ Count * 61000,
                     Variable == "False_Positive" ~ Count * (-2850))) %>%
  bind_cols(data.frame(Description = c(
    "Predicted homeowner would not take credit, no credit was allocated",
    "Predicted homeowner would take the credit, allocated marketing resources and credit, and 25% took the credit",
    "We predicted homeowner would not take the credit, credit was allocated",
    "Predicted homeowner would take credit, allocated marketing resources but not credit")))

kable(cost_benefit_table) %>% 
  kable_styling(font_size = 12, full_width = F,
                bootstrap_options = c("striped", "hover", "condensed")) %>%
  footnote(general_title = "\n",
           general = "Table 6.1")

```

## Threshold Analysis

```{r threshold}

whichThreshold <- 
  iterateThresholds(
    data=testProbs_eng, observedClass = Outcome, predictedProbs = Probs)

whichThreshold[1:5,]
whichThreshold <- 
  whichThreshold %>%
  dplyr::select(starts_with("Count"), Threshold) %>%
  gather(Variable, Count, -Threshold) %>%
  mutate(Revenue =
           case_when(Variable == "Count_TN"  ~ Count * 0,
                     Variable == "Count_TP"  ~ Count * 8650,
                     Variable == "Count_FN" ~ Count * 61000,
                     Variable == "Count_FP" ~ Count * (-2850)))

whichThreshold %>%
  ggplot(.,aes(Threshold, Revenue, colour = Variable)) +
  geom_point() +
  scale_colour_manual(values = palette5[c(5, 1:3)]) +    
  labs(title = "Benefit by confusion matrix type and threshold",
       y = "Benefit") +
  plotTheme() +
  guides(colour=guide_legend(title = "Confusion Matrix"))

```

## Threshhold as a function of benefit and number of credits

```{r threshold plots}
whichThreshold_benefit <- 
  whichThreshold %>% 
  mutate(actualCredit = ifelse(Variable == "Count_TP", (Count * .25),
                              ifelse(Variable == "Count_FN", Count, 0))) %>% 
  group_by(Threshold) %>% 
  summarize(Total_Benefit = sum(Revenue),
            Total_Count_of_Credits = sum(actualCredit))

View(whichThreshold_benefit)

#optimal is 18%

            # Actual_Credit_Rate = sum(actualCredit) / sum(Count),
            # Actual_Credit_Revenue_Loss =  sum(actualCredit * 0),
            # Revenue_Next_Period = Revenue - Actual_Credit_Revenue_Loss) 



#these are ugly and likely incorrect

grid.arrange(ncol=2,
ggplot(data=whichThreshold_benefit,
       aes(x = Threshold, y = Total_Benefit)) +geom_line() +  scale_colour_manual(values = palette2) +plotTheme(),

ggplot(data=whichThreshold_benefit,
       aes(x = Threshold, y =  Total_Count_of_Credits)) +geom_line() + scale_colour_manual(values = palette2) +
 plotTheme())


```

## Benefit and Alloction Comparison across thresholds


```{r revenue and credit table}

threshold_table <- 
  subset(whichThreshold_benefit, Threshold == 0.95| Threshold == 0.50 | Threshold == 0.18)%>%
  mutate(Benefit_per_Credit=Total_Benefit/Total_Count_of_Credits)

kable(threshold_table) %>% 
  kable_styling(font_size = 12, full_width = F,
                bootstrap_options = c("striped", "hover", "condensed")) %>%
  footnote(general_title = "\n",
           general = "Table 6.1")

```


